name: GH-Pages
on:
  - push
jobs:
  linux:
    name: GH-Pages - Linux - ${{ matrix.compiler }}
    runs-on: ubuntu-22.04
    timeout-minutes:
      60
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        include:
          - compiler: ghc-9.6.1
            compilerKind: ghc
            compilerVersion: 9.6.1
            setup-method: ghcup
            allow-failure: false
      fail-fast: false
    steps:
      - name: Setup toolchain
        run: |
        ghcup install cabal --set recommended
        ghcup install ghc --set ${{ matrix.ghc }}
      - name: generate cabal.project
        run: |
          rm -f cabal.project cabal.project.local
          touch cabal.project
          cat >> cabal.project <<EOF
          packages: .

          allow-newer: vector-circular:vector,
          allow-newer: vector-circular:base,
          allow-newer: vector-circular:template-haskell,
          allow-newer: vector-circular:semigroupoids,
          allow-newer: miso:servant,
          allow-newer: servant-lucid:servant,
          allow-newer: lucid-svg:transformers,

          source-repository-package
            type:     git
            location: https://github.com/noinia/hgeometry
            tag:      caed0eed5244da54ba44b064a077f47ca9ce50c6
            subdir:   hgeometry-combinatorial
          EOF
          cat cabal.project

      - name: restore cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-${{ matrix.compiler }}-
      - name: build
        run: |
          cabal update
          cabal build hiraffe
      - name: haddock
        run: |
          ./haddock.sh
      - name: copy-to-pages
        run: |
          mkdir --parents pages/docs/
          cp -r haddocks pages/docs/
          cp haddock.txt pages/
          cp haddock_badge.json pages/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs # The branch the action should deploy to.
          folder: pages # The folder the action should deploy.

      - name: save cache
        uses: actions/cache/save@v3
        if: always()
        with:
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
          path: ~/.cabal/store
